### ISSUE TITLE
Share CAMELYON16 Benchmark

### ISSUE THREAD

**Issue by Reza-Safdari** [sbelharbi/negev#2]
Hi there,
We are currently working on a paper in the WSOL domain and plan to compare our results with the following papers authored by your team:
1) Negative Evidence Matters in Interpretable Histology Image Classification
2) Deep Interpretable Classification and Weakly-Supervised Segmentation of Histology Images via Max-Min Uncertainty
3) Deep Weakly-Supervised Learning Methods for Classification and Localization in Histology Images: A Survey

In your last paper, you presented a concise protocol for sampling small sub-images for WSL with pixel-wise and image-level annotation from the CAMELYON16 dataset. Due to the substantial size of this dataset, we are facing challenges in downloading and running your script to sample small sub-images. May I kindly request that you share the benchmark generated based on your protocol? The benchmark should include a total of 48,870 samples, with 24,348 samples for training, 8,858 samples for validation, and 15,664 samples for testing. Your assistance in this matter would be greatly appreciated.

**Comment by sbelharbi** [comment]
hi,
here is camelyon16 patches (22gb) split into 5 parts:
1- https://www.transfernow.net/dl/20231124WRDBN8Xj/vnsNJTsp
2- https://www.transfernow.net/dl/20231124JZyp2LBv/GEG5OHz3
3- https://www.transfernow.net/dl/202311249hyzS2ga/R99tinmg
4- https://www.transfernow.net/dl/20231124MCuDsAG5/ooJZtMi7
5- https://www.transfernow.net/dl/20231124iMxBUQit/eeKZ4wPx
links expire in 7 days.
once downloaded, run the following to join the parts:
``cat CAMELYON512.tar.gz.parta* > Joined.tar.gz``
thanks

**Comment by Reza-Safdari** [comment]
Thank you so much.

**Comment by sbelharbi** [comment]
closing.
